title = "Silas blog"
baseURL = 'https://silasblog.me'

# Este es el código de idioma de la página
languageCode = 'es'

# Establece el idioma de contenido predeterminado
defaultContentLanguage = "es"

# Habilitar emojis globalmente
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # Ignorar el error de carga de scripts adicionales.

# Forma tradicional: el tema reside en el directorio 'themes'
theme = "hugo-blog-awesome"

[services]
# Para habilitar Google Analytics 4 (gtag.js) proporciona G-MEASUREMENT_ID a continuación.
[services.googleAnalytics]
  id = '' # G-MEASUREMENT_ID

# Para habilitar los comentarios de Disqus, proporciona el Shortname de Disqus a continuación.
[services.disqus]
  shortname = ''

# Configuración del resaltado de código
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

############################## Español ################################
[Languages.es]
  languageName = "Español"
  languageCode = "es"
  contentDir = "content/es"
  weight = 1

  [Languages.es.menu]
  [[Languages.es.menu.main]]
    pageRef="/"
    name = 'Inicio'
    url = '/'
    weight = 10
  [[Languages.es.menu.main]]
    pageRef="posts"
    name = 'Publicaciones'
    url = '/posts/'
    weight = 20
  [[Languages.es.menu.main]]
    pageRef="about"
    name = 'Sobre mí'
    url = '/about/'
    weight = 30

[Languages.es.params]
  sitename = "Blog de SIlas"
  defaultColor = "dark"
  description = "Soy Silas R, una persona multifacética con intereses variados. Actualmente estoy cursando una Maestría en Artes de Estudios Bíblicos, lo que refleja mi pasión por el aprendizaje profundo y las perspectivas espirituales. En el ámbito profesional, soy desarrollador de software, combinando creatividad y lógica para crear soluciones tecnológicas.
Además, soy un gran aficionado al software libre, especialmente en el mundo GNU/Linux, porque creo en la filosofía de la colaboración abierta y el acceso equitativo a las herramientas tecnológicas.
Por último, también soy un escritor casi frustrado, siempre buscando las palabras adecuadas para dar forma a las ideas que rondan mi mente. Este blog es mi forma de canalizar esa pasión y conectar con quienes comparten intereses similares."
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = "2 de enero de 2006"
  rssFeedDescription = "summary"

[Languages.es.params.author]
  avatar = "avatar.jpg"
  intro = "Silas blog"
  name = "Silas R"
  description = "Un espacio para compartir de todo un poco"

[Languages.es.params.webmanifest]
  name = "sitename"
  short_name = "sitename"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"
